<a href="https://colab.research.google.com/github/weirdmusic657/LJuice/blob/main/Copy_of_Week_1_Homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 ### Dave Lewis

Please add your name to this markdown cell.

## Submitting your homework!

Two steps are required for this week's homework once you have completed it:

- __Share__ this notebook with _libraryjuicepresspython@gmail.com_ so it can be marked in Colab
- __Print as PDF__ and upload to the the week's homework submission location on the Library Juice Academy LMS

# Advanced Python - Week 1 Homework

(Be sure to save this to Drive before starting)

For this week we are going to practice requesting information from an API and manipulating it as JSON and as a Dataframe.

We are going to keep working with Collection Builder. Head over to the [Collection Builder Example Projects](https://collectionbuilder.github.io/cb-examples/browse.html) listing and find a site that interests you. Spend some time browsing the website to get acquainted with its contents before proceeding with the questions.

In [ ]:
#The Libraries we will need
import requests
import json
import pandas as pd
from random import randrange

In [ ]:
# @markdown **H1** Find the URL of for the  _metadata.json_ of your selected site and paste it in here.
json_cb_url = "https://thecdil.github.io/ghana-music-initiative/assets/data/metadata.json" # @param {"type":"string","placeholder":""}

response_cb = requests.get(json_cb_url)
#all of the data from the sites
total_cb_data = response_cb.json()
#just the 'objects' indexed in the site
objects_cb_data = total_cb_data['objects']
print("Data fetched and JSON constructed!")

Data fetched and JSON constructed!

**H2** Run the 'show random cell' a few times to get a sense of what kind of data is in your chosen site.

In [ ]:
#Run this a few times to see random entries in the JSON data that you retrieved.
random_entry = randrange(len(objects_cb_data))
print(json.dumps(objects_cb_data[random_entry],indent=2))

{
  "title": "Nunya Music Percussion Ensemble",
  "creator": "Barry Bilderback",
  "date": "2018",
  "description": "The Nunya Music Academy under the direction of Prosper Gbolonyo. Seen in the photograph (left to right): kidi, sogo, kagan, atsime\u028bu. A djembe is also in front of the sogo.",
  "subject": "brass; Dzodze; kidi; sogo; kagan; atsime\u028bu; E\u028be",
  "location": "Dzodze",
  "latitude": "6.242182467",
  "longitude": "0.9961079052",
  "source": "Barry Bilderback Personal Ethnomusicology Record",
  "identifier": "uighana-025",
  "type": "Image;StillImage",
  "format": "image/jpg",
  "rights": "Educational use includes non-commercial use of text and images in materials for teaching and research purposes. Digital reproduction rights granted by the University of Idaho Library. For other uses beyond free use, please contact University of Idaho Library Special Collections and Archives Department.",
  "rightsstatement": "http://rightsstatements.org/vocab/NoC-US/1.0/",
  "object_thumb": "https://www.lib.uidaho.edu/digital/objects/ghana-music/thumbs/uighana-025_th.jpg",
  "object_download": "https://www.lib.uidaho.edu/digital/objects/ghana-music/uighana-025.jpg",
  "reference_url": "https://thecdil.github.io/ghana-music-initiative/items/uighana-025.html"
}

## Different Fields!

You can create any number of datafields and correpsonding values for those fields with a Collection Builder site. So the results from the output from the cell above will probably have wildly different results from [my site](https://elibtronic.github.io/AIL_Database/data.html) that we worked on in the Workalong notebook.


You can see all of these options from grabbing the _facets.json_ URL from a collection builder homepage. Find that URL for your selected site for **H3**

In [ ]:
# @markdown **H3** Find the URL of the facets.json for your selected site and paste it in here.
json_cb_facets_url = "https://thecdil.github.io/ghana-music-initiative/assets/data/facets.json" # @param {"type":"string","placeholder":""}

response_cb = requests.get(json_cb_facets_url)
#all of the data from the sites
total_facet_data = response_cb.json()
#just the 'objects' indexed in the site
print("Data fetched and JSON constructed!")

Data fetched and JSON constructed!

Run the cell below to see what the facets used for this site:

In [ ]:
print(json.dumps(total_facet_data,indent=2))

{
  "facets": [
    {
      "field": "subject",
      "terms": {
        "ga": 17,
        "e\u028be": 17,
        "dance": 11,
        "\u019eono": 9,
        "atswereshie": 9,
        "kpanlogo": 8,
        "shekeshe": 7,
        "kagan": 6,
        "dagbamba": 5,
        "sogo": 4,
        "accra": 4,
        "nungua": 4,
        "ensemble": 4,
        "kidi": 3,
        "homowo": 3,
        "harvest": 3,
        "tamale": 3,
        "brass": 3,
        "dzodze": 3,
        "tubano": 2,
        "gome": 2,
        "akan": 2,
        "adzogbo": 2,
        "tuba": 2,
        "horn": 2,
        "trumpet": 2,
        "trombone": 2,
        "senegal": 1,
        "sobima": 1,
        "sanka": 1,
        "gahu": 1,
        "kpatsa": 1,
        "femefeme": 1,
        "shekshe": 1,
        "setse": 1,
        "mba": 1,
        "volta": 1,
        "ceremonial dance": 1,
        "northern": 1,
        "instruments": 1,
        "ashanti": 1,
        "houses": 1,
        "recreation": 1,
        "kpeve": 1,
        "ceremony": 1,
        "atopani": 1,
        "atsime\u028bu": 1
      }
    },
    {
      "field": "creator",
      "terms": {
        "barry bilderback": 17,
        "felix akusa adjetey sowah": 9,
        "allan fraser \u2013 strobilus": 1,
        "accra : survey division": 1,
        "figlio di dio": 1
      }
    },
    {
      "field": "format",
      "terms": {
        "image/jpg": 17,
        "video/mp4": 12
      }
    }
  ]
}

**H3** Try to read the JSON that is displayed to the screen. What possible facets are there in the the data. Fill them in the markdown list in the cell below. Add as many entries as you need to describe the site

Facets in my site are:
- subject
- creator
- format

**H4** Which facet shows up the most for your selected site? Put your answer in the cell below


This facet that shows up the most is ga (subject), image/jpg (format), and barry bilderback (creator) and they are used 17 times each on my selected site.

**H5** Turn the site _metadata.json_ data into a dataframe by completing the cell below. Part of it is written for you. You just need to modify line 4.

In [ ]:
#H5

cb_data = pd.read_json(json_cb_url)
cb_normalized = pd.json_normalize(cb_data['objects'])
cb_normalized

,title,creator,date,description,subject,location,latitude,longitude,source,identifier,type,format,rights,rightsstatement,object_thumb,object_download,reference_url
0,Senegal,Felix Akusa Adjetey Sowah,2005,The Teshie-Nungua Cultural Dance Troupe perfor...,dance; Ga; Senegal; tubano; ƞono; atswereshie;...,Accra,5.55,-0.2,Barry Bilderback Personal Ethnomusicology Record,uighana-006a,Image;MovingImage,video/mp4,Educational use includes non-commercial use of...,http://rightsstatements.org/vocab/NoC-US/1.0/,https://img.youtube.com/vi/YStk0XusxJA/mqdefau...,https://youtu.be/YStk0XusxJA,https://thecdil.github.io/ghana-music-initiati...
1,Sobima,Felix Akusa Adjetey Sowah,2005,The Teshie-Nungua Cultural Dance Troupe perfor...,dance; Ga; Sobima; ƞono; shekeshe; atswereshie...,Accra,5.55,-0.2,Barry Bilderback Personal Ethnomusicology Record,uighana-006b,Image;MovingImage,video/mp4,Educational use includes non-commercial use of...,http://rightsstatements.org/vocab/NoC-US/1.0/,https://img.youtube.com/vi/ZCiWLWlefHA/mqdefau...,https://youtu.be/ZCiWLWlefHA,https://thecdil.github.io/ghana-music-initiati...
2,Sanka,Felix Akusa Adjetey Sowah,2005,The Teshie-Nungua Cultural Dance Troupe perfor...,dance; Ga; Sanka; tubano; ƞono; shekeshe; atsw...,Accra,5.55,-0.2,Barry Bilderback Personal Ethnomusicology Record,uighana-006c,Image;MovingImage,video/mp4,Educational use includes non-commercial use of...,http://rightsstatements.org/vocab/NoC-US/1.0/,https://img.youtube.com/vi/Oi8ndqgsL5s/mqdefau...,https://youtu.be/Oi8ndqgsL5s,https://thecdil.github.io/ghana-music-initiati...
3,Gahu,Felix Akusa Adjetey Sowah,2005,The Teshie-Nungua Cultural Dance Troupe perfor...,dance; Eʋe; Gahu; ƞono; shekeshe; Eʋe; sogo; k...,Accra,5.55,-0.2,Barry Bilderback Personal Ethnomusicology Record,uighana-006d,Image;MovingImage,video/mp4,Educational use includes non-commercial use of...,http://rightsstatements.org/vocab/NoC-US/1.0/,https://img.youtube.com/vi/KCi0AeMaB94/mqdefau...,https://youtu.be/KCi0AeMaB94,https://thecdil.github.io/ghana-music-initiati...
4,Kpanlogo,Felix Akusa Adjetey Sowah,2005,The Teshie-Nungua Cultural Dance Troupe perfor...,dance; Ga; Kpanlogo; ƞono; shekeshe; atswereshie;,Accra,5.55,-0.2,Barry Bilderback Personal Ethnomusicology Record,uighana-006e,Image;MovingImage,video/mp4,Educational use includes non-commercial use of...,http://rightsstatements.org/vocab/NoC-US/1.0/,https://img.youtube.com/vi/9dwwWZ3_5j4/mqdefau...,https://youtu.be/9dwwWZ3_5j4,https://thecdil.github.io/ghana-music-initiati...
5,Kpatsa,Felix Akusa Adjetey Sowah,2005,The Teshie-Nungua Cultural Dance Troupe perfor...,dance; Ga; Eʋe; Kpatsa; ƞono; shekeshe; atswer...,Accra,5.55,-0.2,Barry Bilderback Personal Ethnomusicology Record,uighana-006f,Image;MovingImage,video/mp4,Educational use includes non-commercial use of...,http://rightsstatements.org/vocab/NoC-US/1.0/,https://img.youtube.com/vi/lQGR00TzfaA/mqdefau...,https://youtu.be/lQGR00TzfaA,https://thecdil.github.io/ghana-music-initiati...
6,Femefeme,Felix Akusa Adjetey Sowah,2005,The Teshie-Nungua Cultural Dance Troupe perfor...,dance; Ga; Femefeme; ƞono; shekshe; atswereshi...,Accra,5.55,-0.2,Barry Bilderback Personal Ethnomusicology Record,uighana-006g,Image;MovingImage,video/mp4,Educational use includes non-commercial use of...,http://rightsstatements.org/vocab/NoC-US/1.0/,https://img.youtube.com/vi/edQjlG5SfzA/mqdefau...,https://youtu.be/edQjlG5SfzA,https://thecdil.github.io/ghana-music-initiati...
7,Setse,Felix Akusa Adjetey Sowah,2005,The Teshie-Nungua Cultural Dance Troupe perfor...,dance; Ga; Setse; Eʋe; mba; ƞono; shekeshe; at...,Accra,5.55,-0.2,Barry Bilderback Personal Ethnomusicology Record,uighana-006h,Image;MovingImage,video/mp4,Educational use includes non-commercial use of...,http://rightsstatements.org/vocab/NoC-US/1.0/,https://img.youtube.com/vi/Yscjl7u56kA/mqdefau...,https://youtu.be/Yscjl7u56kA,https://thecdil.github.io/ghana-music-initiati...
8,Gome,Felix Akusa Adjetey Sowah,2005,The Teshie-Nungua Cultural Dance Troupe perfor...,dance; Ga; Gome; shekeshe; ƞono; gome; atswere...,Accra,5.55,-0.2,Barry Bilderback Personal Ethnomusicology Record,uighana-006i,Image;MovingImage,video/mp4,Educational use includes non-commercial use of...,http://rightsstatements.org/vocab/NoC-US/1.0/,https://img.youtube.com/vi/mHZNUod80KE/mqdefau...,https://youtu.be/mHZNUod80KE,https://thecdil.github.io/ghana-music-initiati...
9,Kpanlogo Drum,Allan Fraser – Strobilus,2007-04-02,Musician playing two kpanlogo (atswereshie) dr...,dance; Kpanlogo; Ga; atswereshie,Accra,5.55,-0.205,Wikimedia Commons,uighana-007,Image;StillImage,image/jpg,Educational use includes non-commercial use of...,http://rightsstatements.org/vocab/NoC-US/1.0/,https://www.lib.uidaho.edu/digital/objects/gha...,https://www.lib.uidaho.edu/digital/objects/gha...,https://thecdil.github.io/ghana-music-initiati...
10,Ehtnicities of Ghana,Accra : Survey Division,1966,Map showing the predmoninant boundaries of var...,Ga; Akan; Dagbamba; Eʋe,Accra,5.55,-0.205,"Library of Congress, http://hdl.loc.gov/loc.gm...",uighana-008,Image;StillImage,image/jpg,Educational use includes non-commercial use of...,http://rightsstatements.org/vocab/NoC-US/1.0/,https://www.lib.uidaho.edu/digital/objects/gha...,https://www.lib.uidaho.edu/digital/objects/gha...,https://thecdil.github.io/ghana-music-initiati...
11,Kpando Dancer,Barry Bilderback,2018,A dancer in the Kpando village prepares for a ...,Eʋe; Volta; ceremonial dance;,Kpando,6.994797409,0.2944420481,Barry Bilderback Personal Ethnomusicology Record,uighana-011,Image;StillImage,image/jpg,Educational use includes non-commercial use of...,http://rightsstatements.org/vocab/NoC-US/1.0/,https://www.lib.uidaho.edu/digital/objects/gha...,https://www.lib.uidaho.edu/digital/objects/gha...,https://thecdil.github.io/ghana-music-initiati...
12,Tamale Circular Dance,Barry Bilderback,2018,Dancers in Tamale gather in a circle for a com...,Dagbamba; northern;,Tamale,9.400722322,-0.8377277218,Barry Bilderback Personal Ethnomusicology Record,uighana-012,Image;StillImage,image/jpg,Educational use includes non-commercial use of...,http://rightsstatements.org/vocab/NoC-US/1.0/,https://www.lib.uidaho.edu/digital/objects/gha...,https://www.lib.uidaho.edu/digital/objects/gha...,https://thecdil.github.io/ghana-music-initiati...
13,Kusun Cultral Center: Ga Perform Eʋe,Barry Bilderback,2018,Dancers at the Kusun Cultural Center in Nungua...,Accra; Ga; Eʋe; Nungua,"Nungua, Accra",5.602882059,-0.1862804716,Barry Bilderback Personal Ethnomusicology Record,uighana-013,Image;StillImage,image/jpg,Educational use includes non-commercial use of...,http://rightsstatements.org/vocab/NoC-US/1.0/,https://www.lib.uidaho.edu/digital/objects/gha...,https://www.lib.uidaho.edu/digital/objects/gha...,https://thecdil.github.io/ghana-music-initiati...
14,Kusun Cultral Center: Ga Perform Eʋe,Barry Bilderback,2018,Dancers at the Kusun Cultural Center in Nungua...,Accra; Ga; Eʋe; Nungua,"Nungua, Accra",5.602882059,-0.1862804716,Barry Bilderback Personal Ethnomusicology Record,uighana-014,Image;StillImage,image/jpg,Educational use includes non-commercial use of...,http://rightsstatements.org/vocab/NoC-US/1.0/,https://www.lib.uidaho.edu/digital/objects/gha...,https://www.lib.uidaho.edu/digital/objects/gha...,https://thecdil.github.io/ghana-music-initiati...
15,Kusun Cultral Center: Ga Perform Eʋe,Barry Bilderback,2018,Dancers at the Kusun Cultural Center in Nungua...,Accra; Ga; Eʋe; Nungua; adzogbo;,"Nungua, Accra",5.602882059,-0.1862804716,Barry Bilderback Personal Ethnomusicology Record,uighana-015,Image;StillImage,image/jpg,Educational use includes non-commercial use of...,http://rightsstatements.org/vocab/NoC-US/1.0/,https://www.lib.uidaho.edu/digital/objects/gha...,https://www.lib.uidaho.edu/digital/objects/gha...,https://thecdil.github.io/ghana-music-initiati...
16,Kusun Cultral Center: Ga Perform Eʋe,Barry Bilderback,2018,Dancers at the Kusun Cultural Center in Nungua...,Accra; Ga; Eʋe; Nungua; adzogbo;,"Nungua, Accra",5.602882059,-0.1862804716,Barry Bilderback Personal Ethnomusicology Record,uighana-016,Image;StillImage,image/jpg,Educational use includes non-commercial use of...,http://rightsstatements.org/vocab/NoC-US/1.0/,https://www.lib.uidaho.edu/digital/objects/gha...,https://www.lib.uidaho.edu/digital/objects/gha...,https://thecdil.github.io/ghana-music-initiati...
17,Homowo Festival,Barry Bilderback,2018,Elders dressed in white process through the ro...,Homowo; Ga; harvest;,Prampram,5.724073591,0.1134711943,Barry Bilderback Personal Ethnomusicology Record,uighana-017,Image;StillImage,image/jpg,Educational use includes non-commercial use of...,http://rightsstatements.org/vocab/NoC-US/1.0/,https://www.lib.uidaho.edu/digital/objects/gha...,https://www.lib.uidaho.edu/digital/objects/gha...,https://thecdil.github.io/ghana-music-initiati...
18,Akan Instruments at the Manhyia Palace Museum,Barry Bilderback,2018,Various drums on display at the Manhyia Palace...,Akan; instruments; Ashanti,Kumasi,6.703624138,-1.615832474,Barry Bilderback Personal Ethnomusicology Record,uighana-018,Image;StillImage,image/jpg,Educational use includes non-commercial use of...,http://rightsstatements.org/vocab/NoC-US/1.0/,https://www.lib.uidaho.edu/digital/objects/gha...,https://www.lib.uidaho.edu/digital/objects/gha...,https://thecdil.github.io/ghana-music-initiati...
19,Tamale Houses,Barry Bilderback,2018,Houses in Tamale indicative by the clay walls ...,Dagbamba; Tamale; houses,Tamale,9.400722322,-0.8377277218,Barry Bilderback Personal Ethnomusicology Record,uighana-019,Image;StillImage,image/jpg,Educational use includes non-commercial use of...,http://rightsstatements.org/vocab/NoC-US/1.0/,https://www.lib.uidaho.edu/digital/objects/gha...,https://www.lib.uidaho.edu/digital/objects/gha...,https://thecdil.github.io/ghana-music-initiati...
20,Tamale Drum Ensemble,Barry Bilderback,2018,Four barrell shaped drums of varying sizes are...,Dagbamba; Tamale; ensemble,Tamale,9.400722322,-0.8377277218,Barry Bilderback Personal Ethnomusicology Record,uighana-020,Image;StillImage,image/jpg,Educational use includes non-commercial use of...,http://rightsstatements.org/vocab/NoC-US/1.0/,https://www.lib.uidaho.edu/digital/objects/gha...,https://www.lib.uidaho.edu/digital/objects/gha...,https://thecdil.github.io/ghana-music-initiati...
21,Tamale Recreational Dance,Barry Bilderback,2018,A recreational ring dance comprised of side-st...,Dagbamba; Tamale; ensemble; recreation; dance,Tamale,9.400722322,-0.8377277218,Barry Bilderback Personal Ethnomusicology Record,uighana-021,Image;MovingImage,video/mp4,Educational use includes non-commercial use of...,http://rightsstatements.org/vocab/NoC-US/1.0/,https://img.youtube.com/vi/ncTqGOU0DOM/mqdefau...,https://youtu.be/ncTqGOU0DOM,https://thecdil.github.io/ghana-music-initiati...
22,Hunor Gatukpe Dogah and Eʋe Drum Ensemble in t...,Barry Bilderback,2018,A drum ensemble in the Volta region performs f...,Kpeve; Eʋe; ensemble; ceremony; atopani,Kpeve,6.685259058,0.3325510045,Barry Bilderback Personal Ethnomusicology Record,uighana-022,Image;MovingImage,video/mp4,Educational use includes non-commercial use of...,http://rightsstatements.org/vocab/NoC-US/1.0/,https://img.youtube.com/vi/XPjZwzRKRi8/mqdefau...,https://youtu.be/XPjZwzRKRi8,https://thecdil.github.io/ghana-music-initiati...
23,Nunya Music Academy Brass Band,Barry Bilderback,2018,The Nunya Music Academy Brass Band performs un...,brass; Dzodze; Eʋe; tuba; horn; trumpet; tromb...,Dzodze,6.242182467,0.9961079052,Barry Bilderback Personal Ethnomusicology Record,uighana-023,Image;StillImage,image/jpg,Educational use includes non-commercial use of...,http://rightsstatements.org/vocab/NoC-US/1.0/,https://www.lib.uidaho.edu/digital/objects/gha...,https://www.lib.uidaho.edu/digital/objects/gha...,https://thecdil.github.io/ghana-music-initiati...
24,Nunya Music Academy Brass Band,Barry Bilderback,2018,The Nunya Music Academy Brass Band performs un...,brass; Dzodze; Eʋe; tuba; horn; trumpet; tromb...,Dzodze,6.242182467,0.9961079052,Barry Bilderback Personal Ethnomusicology Record,uighana-024,Image;StillImage,image/jpg,Educational use includes non-commercial use of...,http://rightsstatements.org/vocab/NoC-US/1.0/,https://www.lib.uidaho.edu/digital/objects/gha...,https://www.lib.uidaho.edu/digital/objects/gha...,https://thecdil.github.io/ghana-music-initiati...
25,Nunya Music Percussion Ensemble,Barry Bilderback,2018,The Nunya Music Academy under the direction of...,brass; Dzodze; kidi; sogo; kagan; atsimeʋu; Eʋe,Dzodze,6.242182467,0.9961079052,Barry Bilderback Personal Ethnomusicology Record,uighana-025,Image;StillImage,image/jpg,Educational use includes non-commercial use of...,http://rightsstatements.org/vocab/NoC-US/1.0/,https://www.lib.uidaho.edu/digital/objects/gha...,https://www.lib.uidaho.edu/digital/objects/gha...,https://thecdil.github.io/ghana-music-initiati...
26,Homowo Procession,Barry Bilderback,2018,Elders dressed in white process through the ro...,Homowo; Ga; harvest;,Prampram,5.724073591,0.1134711943,Barry Bilderback Personal Ethnomusicology Record,uighana-026,Image;MovingImage,video/mp4,Educational use includes non-commercial use of...,http://rightsstatements.org/vocab/NoC-US/1.0/,https://img.youtube.com/vi/0Rg02iJHTl0/mqdefau...,https://youtu.be/0Rg02iJHTl0,https://thecdil.github.io/ghana-music-initiati...
27,Ga Ensemble at Homowo,Barry Bilderback,2018,"Ga musicians seen performing on custom drums, ...",Homowo; Ga; harvest; ensemble,Prampram,5.724073591,0.1134711943,Barry Bilderback Personal Ethnomusicology Record,uighana-027,Image;StillImage,image/jpg,Educational use includes non-commercial use of...,http://rightsstatements.org/vocab/NoC-US/1.0/,https://www.lib.uidaho.edu/digital/objects/gha...,https://www.lib.uidaho.edu/digital/objects/gha...,https://thecdil.github.io/ghana-music-initiati...
28,A pair of Atumpan drums,Figlio di dio,2017-01-23,Photograph of Atumpan drums,NaN,NaN,NaN,NaN,NaN,NaN,Image;StillImage,image/jpg,"Figlio di dio, CC BY-SA 4.0, via Wikimedia Com...",https://creativecommons.org/licenses/by-sa/4.0/,https://upload.wikimedia.org/wikipedia/commons...,https://upload.wikimedia.org/wikipedia/commons...,https://thecdil.github.io/ghana-music-initiati...

In [ ]:
#Run this a few times to see random entries in your dataframe
cb_normalized.sample(10)

,title,creator,date,description,subject,location,latitude,longitude,source,identifier,type,format,rights,rightsstatement,object_thumb,object_download,reference_url
5,Kpatsa,Felix Akusa Adjetey Sowah,2005,The Teshie-Nungua Cultural Dance Troupe perfor...,dance; Ga; Eʋe; Kpatsa; ƞono; shekeshe; atswer...,Accra,5.55,-0.2,Barry Bilderback Personal Ethnomusicology Record,uighana-006f,Image;MovingImage,video/mp4,Educational use includes non-commercial use of...,http://rightsstatements.org/vocab/NoC-US/1.0/,https://img.youtube.com/vi/lQGR00TzfaA/mqdefau...,https://youtu.be/lQGR00TzfaA,https://thecdil.github.io/ghana-music-initiati...
0,Senegal,Felix Akusa Adjetey Sowah,2005,The Teshie-Nungua Cultural Dance Troupe perfor...,dance; Ga; Senegal; tubano; ƞono; atswereshie;...,Accra,5.55,-0.2,Barry Bilderback Personal Ethnomusicology Record,uighana-006a,Image;MovingImage,video/mp4,Educational use includes non-commercial use of...,http://rightsstatements.org/vocab/NoC-US/1.0/,https://img.youtube.com/vi/YStk0XusxJA/mqdefau...,https://youtu.be/YStk0XusxJA,https://thecdil.github.io/ghana-music-initiati...
8,Gome,Felix Akusa Adjetey Sowah,2005,The Teshie-Nungua Cultural Dance Troupe perfor...,dance; Ga; Gome; shekeshe; ƞono; gome; atswere...,Accra,5.55,-0.2,Barry Bilderback Personal Ethnomusicology Record,uighana-006i,Image;MovingImage,video/mp4,Educational use includes non-commercial use of...,http://rightsstatements.org/vocab/NoC-US/1.0/,https://img.youtube.com/vi/mHZNUod80KE/mqdefau...,https://youtu.be/mHZNUod80KE,https://thecdil.github.io/ghana-music-initiati...
18,Akan Instruments at the Manhyia Palace Museum,Barry Bilderback,2018,Various drums on display at the Manhyia Palace...,Akan; instruments; Ashanti,Kumasi,6.703624138,-1.615832474,Barry Bilderback Personal Ethnomusicology Record,uighana-018,Image;StillImage,image/jpg,Educational use includes non-commercial use of...,http://rightsstatements.org/vocab/NoC-US/1.0/,https://www.lib.uidaho.edu/digital/objects/gha...,https://www.lib.uidaho.edu/digital/objects/gha...,https://thecdil.github.io/ghana-music-initiati...
11,Kpando Dancer,Barry Bilderback,2018,A dancer in the Kpando village prepares for a ...,Eʋe; Volta; ceremonial dance;,Kpando,6.994797409,0.2944420481,Barry Bilderback Personal Ethnomusicology Record,uighana-011,Image;StillImage,image/jpg,Educational use includes non-commercial use of...,http://rightsstatements.org/vocab/NoC-US/1.0/,https://www.lib.uidaho.edu/digital/objects/gha...,https://www.lib.uidaho.edu/digital/objects/gha...,https://thecdil.github.io/ghana-music-initiati...
19,Tamale Houses,Barry Bilderback,2018,Houses in Tamale indicative by the clay walls ...,Dagbamba; Tamale; houses,Tamale,9.400722322,-0.8377277218,Barry Bilderback Personal Ethnomusicology Record,uighana-019,Image;StillImage,image/jpg,Educational use includes non-commercial use of...,http://rightsstatements.org/vocab/NoC-US/1.0/,https://www.lib.uidaho.edu/digital/objects/gha...,https://www.lib.uidaho.edu/digital/objects/gha...,https://thecdil.github.io/ghana-music-initiati...
23,Nunya Music Academy Brass Band,Barry Bilderback,2018,The Nunya Music Academy Brass Band performs un...,brass; Dzodze; Eʋe; tuba; horn; trumpet; tromb...,Dzodze,6.242182467,0.9961079052,Barry Bilderback Personal Ethnomusicology Record,uighana-023,Image;StillImage,image/jpg,Educational use includes non-commercial use of...,http://rightsstatements.org/vocab/NoC-US/1.0/,https://www.lib.uidaho.edu/digital/objects/gha...,https://www.lib.uidaho.edu/digital/objects/gha...,https://thecdil.github.io/ghana-music-initiati...
9,Kpanlogo Drum,Allan Fraser – Strobilus,2007-04-02,Musician playing two kpanlogo (atswereshie) dr...,dance; Kpanlogo; Ga; atswereshie,Accra,5.55,-0.205,Wikimedia Commons,uighana-007,Image;StillImage,image/jpg,Educational use includes non-commercial use of...,http://rightsstatements.org/vocab/NoC-US/1.0/,https://www.lib.uidaho.edu/digital/objects/gha...,https://www.lib.uidaho.edu/digital/objects/gha...,https://thecdil.github.io/ghana-music-initiati...
27,Ga Ensemble at Homowo,Barry Bilderback,2018,"Ga musicians seen performing on custom drums, ...",Homowo; Ga; harvest; ensemble,Prampram,5.724073591,0.1134711943,Barry Bilderback Personal Ethnomusicology Record,uighana-027,Image;StillImage,image/jpg,Educational use includes non-commercial use of...,http://rightsstatements.org/vocab/NoC-US/1.0/,https://www.lib.uidaho.edu/digital/objects/gha...,https://www.lib.uidaho.edu/digital/objects/gha...,https://thecdil.github.io/ghana-music-initiati...
4,Kpanlogo,Felix Akusa Adjetey Sowah,2005,The Teshie-Nungua Cultural Dance Troupe perfor...,dance; Ga; Kpanlogo; ƞono; shekeshe; atswereshie;,Accra,5.55,-0.2,Barry Bilderback Personal Ethnomusicology Record,uighana-006e,Image;MovingImage,video/mp4,Educational use includes non-commercial use of...,http://rightsstatements.org/vocab/NoC-US/1.0/,https://img.youtube.com/vi/9dwwWZ3_5j4/mqdefau...,https://youtu.be/9dwwWZ3_5j4,https://thecdil.github.io/ghana-music-initiati...

**H6** This is for bonus!
Try to write a pandas statement that will display your answer from **H4**. There are plenty of ways to do this, so feel free to use your imagination. What I have started for you here might not work, so feel free to change it as needed.

In [ ]:
cb_normalized[cb_normalized[""] == ""].count()


## All Done!

Congrats you are finished with this week's work. First save as PDF so that you can upload to the Course site then click the `Share` button above and enter `libraryjuicepresspython@gmail.com` so I can get a shared copy of your work.